services:
  build:
    build: .
    container_name: build-sbagen-plus
    platform: linux/amd64
    volumes:
      - .:/sbagen-plus
    working_dir: /sbagen-plus
    command:
      - /bin/sh
      - -c
      - |
        ./linux-build-libs.sh
        ./linux-build-sbagenx.sh
        ./windows-build-libs.sh
        ./windows-build-sbagenx.sh
        ./windows-create-installer.sh

  build-arm64:
    build: .
    container_name: build-sbagen-plus-arm64
    platform: linux/arm64
    volumes:
      - .:/sbagen-plus
    working_dir: /sbagen-plus
    command:
      - /bin/sh
      - -c
      - |
        ./linux-build-libs.sh
        ./linux-build-sbagenx.sh
